enum Addressing {
    Implied,
    Immediate(u8),
    Absolute(u8),
    Zeropage(u8),
    IndexedAbsolute(u16, u8),
    IndexedZeropage(u8, u8),
    Indirect(u16),
    PreindexedIndirect(u8),
    PostindexedIndirect(u8),
    RelativeAddress(u8), // used in conditional branching instructions
}

enum Operations {
    LoadAccumulator,
    LoadX,
    LoadY,
    StoreAccumulator,
    StoreX,
    StoreY,
    TransferAccumulatorToX,
    TransferAccumulatorToY,
    TransferStackPointerToX,
    TransferXToAccumulator,
    TransferYToAccumulator,
    PushAccumulator,
    PushStatusRegister,
    PullAccumulator,
    PullStatusRegister,
    DecrementMemory,
    DecrementX,
    DecrementY,
    IncrementMemory,
    IncrementX,
    IncrementY,
    AddWithCarry,
    SubtractWithCarry,
    AndWithAccumulator,
    ExclusiveOrWithAccumulator,
    InclusiveOrWithAccumulator,
    ArithmeticShiftLeft,
    LogicalShiftLeft,
    RotateLeft,
    RotateRight,
    ClearCarry,
    ClearDecimal,
    ClearInterruptDisable,
    ClearOverflow,
    SetCarry,
    SetDecimal,
    SetInterruptDisable,
    CompareWithAccumulator,
    CompareWithX,
    CompareWithY,
    BranchOnCarryClear,
    BranchOnCarrySet,
    BranchOnEqual,
    BranchOnMinus,
    BranchOnNotEqual,
    BranchOnPlus,
    BranchOnOverflowClear,
    BranchOnOverflowSet,
    Jump,
    JumpSubroutine,
    ReturnFromSubroutine,
    SoftwareInterrupt,
    ReturnFromInterrupt,
    BitTest,
    NoOperation
}

struct Instruction {
    operation : Operations,
    operands : Addressing
}
